In [20]:
%matplotlib inline
from numpy import *
import matplotlib.pyplot as plt
import scipy.linalg as linalg

In [21]:
A1 = array([[4, 2, -3, -1, 2, 1, 0, 0, 0, 0],
           [8, 6, -5, -3, 6, 5, 0, 1, 0, 0],
           [4, 2, -2, -1, 3, 2, -1, 0, 3, 1],
           [0, -2, 1, 5, -1, 3, -1, 1, 9, 4],
           [-4, 2, 6, -1, 6, 7, -3, 3, 2, 3],
           [8, 6, -8, 5, 7, 17, 2, 6, -3, 5],
           [0, 2, -1, 3, -4, 2, 5, 3, 0, 1],
           [16, 10, -11, -9, 17, 34, 2, -1, 2, 2],
           [4, 6, 2, -7, 13, 9, 2, 0, 12, 4],
           [0, 0, -1, 8, -3, -24, -8, 6, 3, -1]
          ])
B1 = array([5, 12, 3, 2, 3, 46, 13, 38, 19, -21])

A2 = array([[4, 2, -4, 0, 2, 4, 0, 0],
           [2, 2, -1, -2, 1, 3, 2, 0],
           [-4, -1, 14, 1, -8, -3, 5, 6],
           [0, -2, 1, 6, -1, -4, -3, 3],
           [2, 1, -8, -1, 22, 4, -10, -3],
           [4, 3, -3, -4, 4, 11, 1, -4],
           [0, 2, 5, -3, -10, 1, 14, 2],
           [0, 0, 6, 3, -3, -4, 2, 19]
          ])

B2 = array([0, -6, 6, 23, 11, -22, -15, 45])

A3 = array([[4, -1, 0, 0, 0, 0, 0, 0, 0, 0],
           [-1, 4, -1, 0, 0, 0, 0, 0, 0, 0],
           [0, -1, 4, -1, 0, 0, 0, 0, 0, 0],
           [0, 0, -1, 4, -1, 0, 0, 0, 0, 0],
           [0, 0, 0, -1, 4, -1, 0, 0, 0, 0],
           [0, 0, 0, 0, -1, 4, -1, 0, 0, 0],
           [0, 0, 0, 0, 0, -1, 4, -1, 0, 0],
           [0, 0, 0, 0, 0, 0, -1, 4, -1, 0],
           [0, 0, 0, 0, 0, 0, 0, -1, 4, -1],
           [0, 0, 0, 0, 0, 0, 0, 0, -1, 4],

          ])

B3 = array([7, 5, -13, 2, 6, -12, 14, -4, 5, -5])

## A B 为线性方程组, x0为初值,e为精度.返回结果矩阵和误差(按题目要求,此处未处理)

In [22]:
def GSiterate(A, B, X0, e):
    B = B.T
    X_k = X0
    'shape (行，列)形式的元组'
    X_k1 = zeros(X0.shape)
    n = B.shape[0] #取行数
    delta = 10 #为当前精度
    k = 0 #循环次数
    k_max = 500 #最大循环次数
    while delta > e:
        '外层为迭代'
        for i in range(n):
            '内层为更新每行所有的值'
            # print i, B[i], A[i,0:i], X_k1[0:i], A[i,i:n], X_k[i:n], A[i,i]
            # print dot(A[i,0:i],X_k1[0:i])
            'A[i,0:i] 与 X_k1[0:i] 都是一维的行/列向量，所以dot()[0]也可以写成dot()'
            X_k1[i] = X_k[i] + 1.0 * ( B[i] - dot(A[i,0:i],X_k1[0:i])[0] - dot(A[i,i:n], X_k[i:n])[0] ) / A[i,i]

        delta = max(abs(X_k1-X_k))
        X_k = X_k1.copy()
        result = X_k.T[0]
        k = k + 1
        if k > k_max:
            print u"迭代次数：%s" % k
            return result,delta
    print u"迭代次数：%s" % k
    return result, delta

In [23]:
def Jiterate(A, B, X0, e):
    B = B.T
    X_k = X0
    'shape (行，列)形式的元组'
    X_k1 = zeros(X0.shape)
    n = B.shape[0] #取行数
    delta = 10 #为当前精度
    k = 0 #循环次数
    k_max = 500 #最大循环次数
    while delta > e:
        '外层为迭代'
        for i in range(n):
            '内层为更新每行所有的值'
            # print i, B[i], A[i,0:i], X_k1[0:i], A[i,i:n], X_k[i:n], A[i,i]
            # print dot(A[i,0:i],X_k1[0:i])
            'A[i,0:i] 与 X_k1[0:i] 都是一维的行/列向量，所以dot()[0]也可以写成dot()'
            X_k1[i] = 1.0 * ( B[i] - dot(A[i,0:i],X_k[0:i])[0] - dot(A[i,i+1:n], X_k[i+1:n])[0] ) / A[i,i]
            # print i,X_k1[i]
            # print

        delta = max(abs(X_k1-X_k))
        X_k = X_k1.copy()
        result = X_k.T[0]
        k = k + 1
        if k > k_max:
            print u"迭代次数：%s" % k
            return result,delta
    print u"迭代次数：%s" % k
    return result, delta

## A B 为线性方程组， x0为初值，e为精度 w为松弛因子

In [24]:
def SORiterate(A, B, X0, e, w):
    B = B.T
    X_k = X0
    'shape (行，列)形式的元组'
    X_k1 = zeros(X0.shape)
    n = B.shape[0] #取行数
    delta = 10 #为当前精度
    k = 0 #循环次数
    k_max = 500 #最大循环次数
    while delta > e:
        '外层为迭代'
        for i in range(n):
            '内层为更新每行所有的值'
            # print i, B[i], A[i,0:i], X_k1[0:i], A[i,i:n], X_k[i:n], A[i,i]
            # print dot(A[i,0:i],X_k1[0:i])
            'A[i,0:i] 与 X_k1[0:i] 都是一维的行/列向量，所以dot()[0]也可以写成dot()'
            X_k1[i] = X_k[i] + w * ( B[i] - dot(A[i,0:i],X_k1[0:i])[0] - dot(A[i,i:n], X_k[i:n])[0] ) / A[i,i]
            # print i,X_k1[i]
            # print

        delta = max(abs(X_k1-X_k))
        X_k = X_k1.copy()
        result = X_k.T[0]
        k = k + 1
        if k > k_max:
            print u"迭代次数：%s" % k
            return result,delta
    print u"迭代次数：%s" % k
    return result, delta

In [25]:
a = A2
b = B2
print b.shape[0]
X0 = array([[(i/i)-1 for i in xrange(1,b.shape[0]+1)]])
X0 = matrix(X0)
X0 = X0.getT()
print "X0: "
print X0
e = 1e-3

8
X0: 
[[0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]]


In [26]:
print "J: "
X1,eX1 = Jiterate(a, b, X0, e)
print X1
print eX1
print "\n\n"

J: 
迭代次数：501
[ -1.46589136e+144  -2.21124013e+144   6.01430752e+143   8.76927509e+143
  -3.57525719e+143  -9.59016349e+143  -3.04938751e+142   3.00681538e+143]
[  3.35065365e+144]





In [27]:
print "GS: "
X2 = GSiterate(a, b, X0, e)
print X2
print "\n\n"

GS: 
迭代次数：133
(array([ 1.16044845, -1.18863123,  0.03768047,  1.91661986,  1.01327152,
       -1.03424435,  0.00822543,  1.99528652]), array([ 0.00099722]))





In [28]:
 print "SOR: "
w = [i/10.0 for i in xrange(8,13)]
for i in w:
    print "in w=%s" % i
    X3 = SORiterate(a, b, X0, e, i)
    print X3


SOR: 
in w=0.8
迭代次数：13
(array([ 1.10399776, -1.11816223,  0.02542281,  1.947348  ,  1.00971978,
       -1.02364351,  0.00589161,  1.99612744]), array([ 0.00073224]))
in w=0.9
迭代次数：14
(array([ 1.19402514, -1.22700843,  0.04589841,  1.89965798,  1.01643703,
       -1.04180431,  0.01016844,  1.99405446]), array([ 0.00096882]))
in w=1.0
迭代次数：133
(array([ 1.16044845, -1.18863123,  0.03768047,  1.91661986,  1.01327152,
       -1.03424435,  0.00822543,  1.99528652]), array([ 0.00099722]))
in w=1.1
迭代次数：197
(array([ 1.13142103, -1.1543482 ,  0.03085899,  1.93177861,  1.01086025,
       -1.02805004,  0.00672304,  1.99613094]), array([ 0.00099861]))
in w=1.2
迭代次数：228
(array([ 1.10679959, -1.12527165,  0.02507298,  1.94463503,  1.00881514,
       -1.02279596,  0.00544894,  1.99684738]), array([ 0.00099652]))


## 使用numpy包中的linalg.solve()方法解多元一次方程

In [29]:
X = linalg.solve(a,b)
print X

[  1.00000000e+00  -1.00000000e+00   6.00577789e-15   2.00000000e+00
   1.00000000e+00  -1.00000000e+00   1.84389892e-15   2.00000000e+00]
